#source 'https://github.com/CocoaPods/Old-Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios
xcodeproj 'AnnotationKitDemo.xcodeproj'
target 'AnnotationKitDemo' do
	platform:ios, '8.0'
    use_frameworks!
    
    pod  'AnnotationKit',     :git => ''
    
    pod  'BussinessOneDylib',       :path=> './BussinessOneDylib'
    pod  'BussinessTwoDylib',       :path=> './BussinessTwoDylib'
end
